// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace ERP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250128154117_fix")]
    partial class fix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true);

            modelBuilder.Entity("Persistence.entities.Client.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("estRestreint")
                        .HasColumnType("INTEGER");

                    b.Property<int>("nbNotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("note")
                        .HasColumnType("REAL");

                    b.Property<float>("sumNotes")
                        .HasColumnType("REAL");

                    b.Property<int>("telephone")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Persistence.entities.Commande.ArticleCommande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("commandeId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("prix")
                        .HasColumnType("REAL");

                    b.Property<int>("produitId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("commandeId");

                    b.HasIndex("produitId");

                    b.ToTable("ArticleCommandes");
                });

            modelBuilder.Entity("Persistence.entities.Commande.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("clientId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("dateCommande")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("clientId");

                    b.ToTable("Commandes");
                });

            modelBuilder.Entity("Persistence.entities.Facturation.Echeance", b =>
                {
                    b.Property<int>("EcheanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("FactureId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MethodePaiement")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Montant")
                        .HasColumnType("REAL");

                    b.Property<int>("StatutEcheance")
                        .HasColumnType("INTEGER");

                    b.HasKey("EcheanceId");

                    b.ToTable("Echeances");
                });

            modelBuilder.Entity("Persistence.entities.Facturation.Facture", b =>
                {
                    b.Property<int>("FactureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("TEXT");

                    b.Property<float>("MontantPayé")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "montantPayé");

                    b.Property<float>("MontantTotal")
                        .HasColumnType("REAL");

                    b.Property<int>("StatusFacture")
                        .HasColumnType("INTEGER");

                    b.HasKey("FactureId");

                    b.HasIndex("CommandeId")
                        .IsUnique();

                    b.ToTable("Factures");
                });

            modelBuilder.Entity("Persistence.entities.Stock.ArticleStock", b =>
                {
                    b.Property<int>("ProduitId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Prix")
                        .HasColumnType("REAL");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProduitId");

                    b.ToTable("AricleStocks");
                });

            modelBuilder.Entity("Persistence.entities.Stock.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Persistence.entities.Stock.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Persistence.entities.Commande.ArticleCommande", b =>
                {
                    b.HasOne("Persistence.entities.Commande.Commande", "commande")
                        .WithMany("articles")
                        .HasForeignKey("commandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence.entities.Stock.Produit", "produit")
                        .WithMany()
                        .HasForeignKey("produitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("commande");

                    b.Navigation("produit");
                });

            modelBuilder.Entity("Persistence.entities.Commande.Commande", b =>
                {
                    b.HasOne("Persistence.entities.Client.Client", "client")
                        .WithMany()
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("client");
                });

            modelBuilder.Entity("Persistence.entities.Facturation.Facture", b =>
                {
                    b.HasOne("Persistence.entities.Commande.Commande", "Commande")
                        .WithOne("Facture")
                        .HasForeignKey("Persistence.entities.Facturation.Facture", "CommandeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Commande");
                });

            modelBuilder.Entity("Persistence.entities.Stock.ArticleStock", b =>
                {
                    b.HasOne("Persistence.entities.Stock.Produit", "Produit")
                        .WithOne("ArticleStock")
                        .HasForeignKey("Persistence.entities.Stock.ArticleStock", "ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");
                });

            modelBuilder.Entity("Persistence.entities.Stock.Produit", b =>
                {
                    b.HasOne("Persistence.entities.Stock.Categorie", "Categorie")
                        .WithMany("Produits")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("Persistence.entities.Commande.Commande", b =>
                {
                    b.Navigation("Facture")
                        .IsRequired();

                    b.Navigation("articles");
                });

            modelBuilder.Entity("Persistence.entities.Stock.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("Persistence.entities.Stock.Produit", b =>
                {
                    b.Navigation("ArticleStock")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
